### ISSUE TITLE
Cannot deploy after updating from 0.1.111 ion to 3.1.49

### ISSUE THREAD

**Issue by NeoFoxxo** [sst/sst#4036]
When I started building my app I installed ion through specifying `ion` in the package.json and it was working fine. 
However when I tried to deploy to prod I got this error: `TypeError: pulumi.runtime.invokeOutput is not a function`. 

So I decided to update to the latest SST version. I ran `pnpm update sst --latest` and ran my usual dev command
`sst dev --stage dev`. 

But now I get even more errors than I got previously only in prod. 

```
|  Error       punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBatmfh aws:apigateway:Resource
|    sdk-v2/provider2.go:509: sdk.helper_schema: creating API Gateway Resource: operation error API Gateway: CreateResource, https response error Stat
usCode: 409, RequestID: 302b0167-98ba-4c2f-b5d2-faed40291a11, ConflictException: Another resource with the same parent already has this name: web: pro
vider=aws@6.54.0
|  Error       punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBabtrc aws:apigateway:Resource
|    sdk-v2/provider2.go:509: sdk.helper_schema: creating API Gateway Resource: operation error API Gateway: CreateResource, https response error Stat
usCode: 409, RequestID: e56654a1-b248-4347-a504-b700fa31925e, ConflictException: Another resource with the same parent already has this name: api: pro
vider=aws@6.54.0
|  Error       punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBatmfh aws:apigateway:Resource
|  Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: 302b0167-98ba-4c2f-b5d2-faed40291a11, Confl
ictException: Another resource with the same parent already has this name: web
|  Error       punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBabtrc aws:apigateway:Resource
|  Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: e56654a1-b248-4347-a504-b700fa31925e, Confl
ictException: Another resource with the same parent already has this name: api

✕  Failed
   punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBatmfh aws:apigateway:Resource
     sdk-v2/provider2.go:509: sdk.helper_schema: creating API Gateway Resource: operation error API Gateway: CreateResource, https response error Stat
usCode: 409, RequestID: 302b0167-98ba-4c2f-b5d2-faed40291a11, ConflictException: Another resource with the same parent already has this name: web: pro
vider=aws@6.54.0

   punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBabtrc aws:apigateway:Resource
     sdk-v2/provider2.go:509: sdk.helper_schema: creating API Gateway Resource: operation error API Gateway: CreateResource, https response error Stat
usCode: 409, RequestID: e56654a1-b248-4347-a504-b700fa31925e, ConflictException: Another resource with the same parent already has this name: api: pro
vider=aws@6.54.0

   punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBatmfh aws:apigateway:Resource
   Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: 302b0167-98ba-4c2f-b5d2-faed40291a11, Confl
ictException: Another resource with the same parent already has this name: web

   punchline-api sst:aws:ApiGatewayV1 → punchline-apiResourceBabtrc aws:apigateway:Resource
   Resource: operation error API Gateway: CreateResource, https response error StatusCode: 409, RequestID: e56654a1-b248-4347-a504-b700fa31925e, Confl
ictException: Another resource with the same parent already has this name: api
```

Its a conflict of some sort so I tried to change the name of the API Gateway but it did not fix the issue. Will I have to delete my entire deployment? Since I don't want to redo adding my SST secrets.

**Comment by srenault** [comment]
Got the same conflict issue on my side:
![Screenshot 2024-10-28 at 12 34 12](https://github.com/user-attachments/assets/1c823500-ef45-4791-ad59-adadcf5cd467)
Not sure how to move on from there. Destoying my stack is not an option.
